# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Black Pearl
author: "parad0x_0xff"
email: "at.ferreira@protonmail.com"
description: Blog Rasquer!
baseurl: ""
url: "http://parad0x-0xff.github.io/" # github pages

# ------------------------------------------------------------------------------
# Custom settings
# ------------------------------------------------------------------------------
# Useful links
github_username: "parad0x-0xff"
facebook_username: "zuck"
twitter_username: "parad0x_0xff"
linkedin_id: "in/ryanroslansky?trk=author_mini-profile_title&challengeId=AQHVAim4lVOTcQAAAXT2UtZxd6mmsWrqUJyqZgGHRxVb_yi5LVfJUzJfxve8-u51BVftxzmBEt484qmaPIoh7YRxT7iCWjCKsg&submissionId=03a07872-99f3-3a16-2a96-cb504675385c"

# Theme
# theme: jekyll-theme-potato-hacker                 # Uncomment this
# remote_theme: luxedo/jekyll-theme-potato-hacker   # Or this
theme_repository: "https://github.com/luxedo/jekyll-theme-potato-hacker"
theme_base: "dark"       # Theme palette (light | dark)
theme_switch: on         # Show color switch (on | off)

# Extra settings
blog: on                 # Show blog tag and post list (on | off)
avatar: on               # Show avatar (on | off)
avatar_image: "assets/img/avatar.jpg"
avatar_description: "Under a black flag we shall sail"
highlighter_theme: gruvbox  # Theme of the syntax_highlighter [base16 |
                            # colorful | github | gruvbox | molokai |
                            # monokai | pastie | thankful_eyes | tulip ]
toolbar_priority:        # Order of the items in the toolbar (except for blog and home)
  #- dropdown2
  #- About
  - dropdown1

# Collections
collections:
  dropdown:
    output: true
  items:
    output: true
# ------------------------------------------------------------------------------


# Build settings
excerpt_separator: "<!--more-->"
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
exclude:
  - Gemfile
  - Gemfile.lock
